from app.db import SessionLocal
from app.models.commerce import Commerce

def seed_commerces():
    db = SessionLocal()
    try:
        if db.query(Commerce).count() == 0:
            commerces = [
                Commerce(
                    code="C-0001",
                    name="Panadería La 85 S.A.S.",
                    location="Bogotá, Cundinamarca",
                    segment="Microempresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cra 85 # 15-20",
                    city="Bogotá",
                    department="Cundinamarca",
                    description="Panadería tradicional con productos frescos diarios.",
                    contact_email="contacto@panaderiala85.com",
                    contact_phone="+5712345678",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Pan, pasteles y productos de panadería"
                ),
                Commerce(
                    code="C-0002",
                    name="Tienda Móvil El Campito",
                    location="Medellín, Antioquia",
                    segment="Microempresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cra 45 # 12-34",
                    city="Medellín",
                    department="Antioquia",
                    description="Tienda móvil con productos variados y entrega rápida.",
                    contact_email="contacto@elcampito.com",
                    contact_phone="+5749876543",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Productos variados, accesorios y alimentos"
                ),
                Commerce(
                    code="C-0003",
                    name="Ferretería Central",
                    location="Cali, Valle del Cauca",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cl 10 # 5-67",
                    city="Cali",
                    department="Valle del Cauca",
                    description="Ferretería con amplia variedad de herramientas y materiales.",
                    contact_email="contacto@ferreteriacentral.com",
                    contact_phone="+5723456789",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Herramientas, materiales de construcción y pinturas"
                ),
                Commerce(
                    code="C-0004",
                    name="Librería El Saber",
                    location="Barranquilla, Atlántico",
                    segment="Microempresa",
                    status="Inactivo",
                    channel="POS Físico",
                    address="Cl 50 # 20-10",
                    city="Barranquilla",
                    department="Atlántico",
                    description="Librería con libros y material escolar.",
                    contact_email="contacto@elsaber.com",
                    contact_phone="+5756789123",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Libros, cuadernos y material escolar"
                ),
                Commerce(
                    code="C-0005",
                    name="Café Aroma",
                    location="Bucaramanga, Santander",
                    segment="Mediana Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cra 30 # 15-40",
                    city="Bucaramanga",
                    department="Santander",
                    description="Cafetería con productos gourmet y venta en línea.",
                    contact_email="contacto@cafearoma.com",
                    contact_phone="+5778912345",
                    risk_level="Alto",
                    avg_monthly_billing=10000000.0,
                    main_products="Café gourmet, pasteles y bebidas"
                ),
                Commerce(
                    code="C-0006",
                    name="Tienda de Ropa Urban Style",
                    location="Bogotá, Cundinamarca",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cra 7 # 85-60",
                    city="Bogotá",
                    department="Cundinamarca",
                    description="Tienda de ropa urbana para jóvenes.",
                    contact_email="contacto@urbanstyle.com",
                    contact_phone="+5713456789",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Ropa urbana, accesorios y calzado"
                ),
                Commerce(
                    code="C-0007",
                    name="Electrodomésticos La Casa",
                    location="Medellín, Antioquia",
                    segment="Mediana Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cl 33 # 10-20",
                    city="Medellín",
                    department="Antioquia",
                    description="Venta online de electrodomésticos y tecnología.",
                    contact_email="contacto@lacasaelectro.com",
                    contact_phone="+5741234567",
                    risk_level="Alto",
                    avg_monthly_billing=10000000.0,
                    main_products="Electrodomésticos, tecnología y accesorios"
                ),
                Commerce(
                    code="C-0008",
                    name="Restaurante El Buen Sabor",
                    location="Cartagena, Bolívar",
                    segment="Microempresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cl 12 # 5-30",
                    city="Cartagena",
                    department="Bolívar",
                    description="Restaurante con comida típica y ambiente familiar.",
                    contact_email="contacto@elbuenabor.com",
                    contact_phone="+5751234567",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Comida típica, platos a la carta y bebidas"
                ),
                Commerce(
                    code="C-0009",
                    name="Joyería Brillantes",
                    location="Cali, Valle del Cauca",
                    segment="Pequeña Empresa",
                    status="Inactivo",
                    channel="E-commerce",
                    address="Cra 15 # 10-22",
                    city="Cali",
                    department="Valle del Cauca",
                    description="Joyería con diseños exclusivos y venta online.",
                    contact_email="contacto@joyeriabrillantes.com",
                    contact_phone="+5729876543",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Joyería fina, anillos, collares y pulseras"
                ),
                Commerce(
                    code="C-0010",
                    name="Farmacia Salud Total",
                    location="Bogotá, Cundinamarca",
                    segment="Mediana Empresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cra 10 # 20-15",
                    city="Bogotá",
                    department="Cundinamarca",
                    description="Farmacia con productos farmacéuticos y asesoría.",
                    contact_email="contacto@farmaciasaludtotal.com",
                    contact_phone="+5715678901",
                    risk_level="Alto",
                    avg_monthly_billing=10000000.0,
                    main_products="Medicamentos, productos de salud y cuidado personal"
                ),
                Commerce(
                    code="C-0011",
                    name="Tienda de Mascotas Pet Lovers",
                    location="Medellín, Antioquia",
                    segment="Microempresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cl 40 # 15-10",
                    city="Medellín",
                    department="Antioquia",
                    description="Tienda online para productos de mascotas.",
                    contact_email="contacto@petlovers.com",
                    contact_phone="+5748765432",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Alimentos y accesorios para mascotas"
                ),
                Commerce(
                    code="C-0012",
                    name="Panadería Dulces Sueños",
                    location="Bucaramanga, Santander",
                    segment="Microempresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cra 25 # 10-5",
                    city="Bucaramanga",
                    department="Santander",
                    description="Panadería artesanal con productos frescos.",
                    contact_email="contacto@dulcessuenos.com",
                    contact_phone="+5771234567",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Pan, pasteles y productos de panadería"
                ),
                Commerce(
                    code="C-0013",
                    name="Tienda de Deportes Sport Life",
                    location="Barranquilla, Atlántico",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cl 45 # 20-15",
                    city="Barranquilla",
                    department="Atlántico",
                    description="Venta online de artículos deportivos y ropa.",
                    contact_email="contacto@sportlife.com",
                    contact_phone="+5752345678",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Artículos deportivos, ropa y calzado"
                ),
                Commerce(
                    code="C-0014",
                    name="Librería Mundo de Libros",
                    location="Cartagena, Bolívar",
                    segment="Microempresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cl 15 # 10-20",
                    city="Cartagena",
                    department="Bolívar",
                    description="Librería con amplio catálogo de libros y revistas.",
                    contact_email="contacto@mundoelibros.com",
                    contact_phone="+5753456789",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Libros, revistas y material escolar"
                ),
                Commerce(
                    code="C-0015",
                    name="Cafetería La Esquina",
                    location="Cali, Valle del Cauca",
                    segment="Microempresa",
                    status="Inactivo",
                    channel="E-commerce",
                    address="Cra 20 # 5-10",
                    city="Cali",
                    department="Valle del Cauca",
                    description="Cafetería con servicio a domicilio y productos frescos.",
                    contact_email="contacto@laesquina.com",
                    contact_phone="+5721234567",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Café, bebidas y snacks"
                ),
                Commerce(
                    code="C-0016",
                    name="Tienda de Juguetes Happy Kids",
                    location="Bogotá, Cundinamarca",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cra 12 # 25-30",
                    city="Bogotá",
                    department="Cundinamarca",
                    description="Tienda especializada en juguetes para niños.",
                    contact_email="contacto@happykids.com",
                    contact_phone="+5718765432",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Juguetes, juegos y productos infantiles"
                ),
                Commerce(
                    code="C-0017",
                    name="Electrónica Tech World",
                    location="Medellín, Antioquia",
                    segment="Mediana Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cl 22 # 10-40",
                    city="Medellín",
                    department="Antioquia",
                    description="Venta online de productos electrónicos y gadgets.",
                    contact_email="contacto@techworld.com",
                    contact_phone="+5742345678",
                    risk_level="Alto",
                    avg_monthly_billing=10000000.0,
                    main_products="Electrónica, gadgets y accesorios tecnológicos"
                ),
                Commerce(
                    code="C-0018",
                    name="Restaurante Mar y Tierra",
                    location="Cartagena, Bolívar",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cl 18 # 10-25",
                    city="Cartagena",
                    department="Bolívar",
                    description="Restaurante con platos de mariscos y carnes.",
                    contact_email="contacto@marytierra.com",
                    contact_phone="+5754567890",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Mariscos, carnes y platos tradicionales"
                ),
                Commerce(
                    code="C-0019",
                    name="Joyería Oro y Plata",
                    location="Bucaramanga, Santander",
                    segment="Microempresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cra 15 # 10-35",
                    city="Bucaramanga",
                    department="Santander",
                    description="Joyería con venta online de piezas exclusivas.",
                    contact_email="contacto@oroyplata.com",
                    contact_phone="+5773456789",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Joyería fina, anillos y pulseras"
                ),
                Commerce(
                    code="C-0020",
                    name="Farmacia Salud y Vida",
                    location="Barranquilla, Atlántico",
                    segment="Mediana Empresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cl 55 # 20-40",
                    city="Barranquilla",
                    department="Atlántico",
                    description="Farmacia con productos de salud y cuidado personal.",
                    contact_email="contacto@saludyvida.com",
                    contact_phone="+5755678901",
                    risk_level="Alto",
                    avg_monthly_billing=10000000.0,
                    main_products="Medicamentos, productos de salud y bienestar"
                ),
                Commerce(
                    code="C-0021",
                    name="Tienda de Ropa Fashion Trend",
                    location="Bogotá, Cundinamarca",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cra 9 # 85-55",
                    city="Bogotá",
                    department="Cundinamarca",
                    description="Tienda online de ropa de moda para jóvenes.",
                    contact_email="contacto@fashiontrend.com",
                    contact_phone="+5714567890",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Ropa de moda, accesorios y calzado"
                ),
                Commerce(
                    code="C-0022",
                    name="Panadería La Dulzura",
                    location="Medellín, Antioquia",
                    segment="Microempresa",
                    status="Activo",
                    channel="POS Físico",
                    address="Cl 30 # 15-20",
                    city="Medellín",
                    department="Antioquia",
                    description="Panadería artesanal con productos dulces y salados.",
                    contact_email="contacto@ladulzura.com",
                    contact_phone="+5743456789",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Pan dulce, pasteles y productos de panadería"
                ),
                Commerce(
                    code="C-0023",
                    name="Tienda de Electrónica ElectroShop",
                    location="Cali, Valle del Cauca",
                    segment="Mediana Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cra 12 # 20-30",
                    city="Cali",
                    department="Valle del Cauca",
                    description="Venta online de productos electrónicos y accesorios.",
                    contact_email="contacto@electroshop.com",
                    contact_phone="+5724567890",
                    risk_level="Alto",
                    avg_monthly_billing=10000000.0,
                    main_products="Electrónica, gadgets y accesorios tecnológicos"
                ),
                Commerce(
                    code="C-0024",
                    name="Cafetería El Rincón",
                    location="Barranquilla, Atlántico",
                    segment="Microempresa",
                    status="Inactivo",
                    channel="POS Físico",
                    address="Cl 60 # 20-15",
                    city="Barranquilla",
                    department="Atlántico",
                    description="Cafetería con ambiente acogedor y productos frescos.",
                    contact_email="contacto@elrincon.com",
                    contact_phone="+5756789012",
                    risk_level="Bajo",
                    avg_monthly_billing=2500000.0,
                    main_products="Café, bebidas y snacks"
                ),
                Commerce(
                    code="C-0025",
                    name="Librería Letras y Más",
                    location="Bogotá, Cundinamarca",
                    segment="Pequeña Empresa",
                    status="Activo",
                    channel="E-commerce",
                    address="Cra 11 # 30-40",
                    city="Bogotá",
                    department="Cundinamarca",
                    description="Librería con venta online de libros y material escolar.",
                    contact_email="contacto@letrasyemas.com",
                    contact_phone="+5715678902",
                    risk_level="Medio",
                    avg_monthly_billing=5000000.0,
                    main_products="Libros, revistas y material escolar"
                )
            ]
            db.add_all(commerces)
            db.commit()
            print("✅ Comercios iniciales creados.")
        else:
            print("ℹ️ Comercios ya existentes, sin cambios.")
    finally:
        db.close()